"""The migration, not `create_all`, is what builds this schema — including in
tests. If the suite built the schema any other way, `alembic check` and the
tests would exercise two different schemas and a migration bug could only be
found in production."""

import asyncio
import logging
from pathlib import Path

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect, text
from sqlalchemy.ext.asyncio import AsyncEngine

from support.db import DATABASE_URL, alembic_config

pytestmark = [pytest.mark.integration, pytest.mark.asyncio(loop_scope="session")]


async def test_the_migration_creates_every_table_the_models_declare(
    migrated_schema: None, engine: AsyncEngine
) -> None:
    async with engine.connect() as connection:
        tables = await connection.run_sync(lambda sync: set(inspect(sync).get_table_names()))
    assert {
        "matches",
        "match_players",
        "match_events",
        "categories",
        "images",
    } <= tables


async def test_models_and_migrations_do_not_disagree(migrated_schema: None) -> None:
    """`alembic check` autogenerates against the live schema and raises if
    anything differs. A column added to a model without a migration fails
    here rather than at the first INSERT in production.

    Two known blind spots this test does not cover, because Alembic itself
    does not compare on them:
    - Check constraint bodies. Alembic's autogenerate signature for a check
      constraint is its name alone (`DefaultImpl.compare_check_constraint`
      always reports equal), so the status check's `status IN (...)` text
      can drift from `MatchStatus` between the model and the migration
      without this test noticing. See `test_the_status_check_admits_
      exactly_the_domain_statuses` in `test_schema.py` for what does catch
      that.
    - Server defaults, unless explicitly requested. `env.py` passes
      `compare_server_default=True` to both `context.configure()` calls so
      this test *does* cover `server_default=func.now()` on `created_at`/
      `occurred_at` — that flag is off by default in Alembic and easy to
      lose in a future edit to `env.py`.
    """
    try:
        await asyncio.to_thread(command.check, alembic_config(DATABASE_URL))
    except AutogenerateDiffsDetected as diffs:  # pragma: no cover - failure path
        pytest.fail(f"models and migrations disagree: {diffs}")


async def test_running_the_migration_leaves_other_loggers_enabled(
    migrated_schema: None, engine: AsyncEngine
) -> None:
    """`env.py` calls `logging.config.fileConfig`, and that function's
    default (`disable_existing_loggers=True`) silently disables every
    logger already alive in the process that its config file does not
    name — every logger but `root`, `sqlalchemy`, and `alembic`. A schema
    migration has no business turning off logging that has nothing to do
    with it, in-process or otherwise, so `env.py` passes
    `disable_existing_loggers=False`. This pins that: a logger created
    before the migration runs must still be enabled after."""
    probe = logging.getLogger("budge.test.migration_logging_probe")
    assert not probe.disabled
    await asyncio.to_thread(command.upgrade, alembic_config(DATABASE_URL), "head")
    assert not probe.disabled


async def test_downgrade_removes_the_schema_and_upgrade_restores_it(
    migrated_schema: None, engine: AsyncEngine
) -> None:
    config = alembic_config(DATABASE_URL)
    await asyncio.to_thread(command.downgrade, config, "base")
    async with engine.connect() as connection:
        tables = await connection.run_sync(lambda sync: set(inspect(sync).get_table_names()))
    assert "match_events" not in tables
    await asyncio.to_thread(command.upgrade, config, "head")
    async with engine.connect() as connection:
        version = (
            await connection.execute(text("SELECT version_num FROM alembic_version"))
        ).scalar_one()
    # Read from the script directory rather than written out: a literal
    # here goes stale on the next migration, and the property under test is
    # "upgrade restored the schema to head", not "head is 0001".
    assert version == ScriptDirectory.from_config(config).get_current_head()


async def test_the_migrate_command_brings_an_empty_database_to_head(
    migrated_schema: None, engine: AsyncEngine, monkeypatch: pytest.MonkeyPatch
) -> None:
    from budge.cli import main

    await asyncio.to_thread(command.downgrade, alembic_config(DATABASE_URL), "base")
    monkeypatch.setenv("BUDGE_DATABASE_URL", DATABASE_URL)
    assert await asyncio.to_thread(main, ["migrate"]) == 0
    async with engine.connect() as connection:
        tables = await connection.run_sync(lambda sync: set(inspect(sync).get_table_names()))
    assert "match_events" in tables


async def test_the_migrate_command_works_from_any_working_directory(
    migrated_schema: None,
    engine: AsyncEngine,
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """`alembic.ini`'s `script_location` is a relative path, and Alembic
    resolves it against the *invocation* directory, not against the ini
    file's own location. An operator applying migrations as a separate step
    (§10) is not guaranteed to be standing in `backend/` — `budge
    migrate` must reach head regardless of the current working directory."""
    from budge.cli import main

    await asyncio.to_thread(command.downgrade, alembic_config(DATABASE_URL), "base")
    monkeypatch.setenv("BUDGE_DATABASE_URL", DATABASE_URL)
    monkeypatch.chdir(tmp_path)
    assert await asyncio.to_thread(main, ["migrate"]) == 0
    async with engine.connect() as connection:
        tables = await connection.run_sync(lambda sync: set(inspect(sync).get_table_names()))
    assert "match_events" in tables
