"""The migration, not `create_all`, is what builds this schema — including in
tests. If the suite built the schema any other way, `alembic check` and the
tests would exercise two different schemas and a migration bug could only be
found in production."""

import asyncio

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect, text
from sqlalchemy.ext.asyncio import AsyncEngine

from support.db import DATABASE_URL, alembic_config

pytestmark = [pytest.mark.integration, pytest.mark.asyncio(loop_scope="session")]


async def test_the_migration_creates_every_table_the_models_declare(
    migrated_schema: None, engine: AsyncEngine
) -> None:
    async with engine.connect() as connection:
        tables = await connection.run_sync(lambda sync: set(inspect(sync).get_table_names()))
    assert {"matches", "match_players", "match_events"} <= tables


async def test_models_and_migrations_do_not_disagree(migrated_schema: None) -> None:
    """`alembic check` autogenerates against the live schema and raises if
    anything differs. A column added to a model without a migration fails
    here rather than at the first INSERT in production."""
    try:
        await asyncio.to_thread(command.check, alembic_config(DATABASE_URL))
    except AutogenerateDiffsDetected as diffs:  # pragma: no cover - failure path
        pytest.fail(f"models and migrations disagree: {diffs}")


async def test_downgrade_removes_the_schema_and_upgrade_restores_it(
    migrated_schema: None, engine: AsyncEngine
) -> None:
    config = alembic_config(DATABASE_URL)
    await asyncio.to_thread(command.downgrade, config, "base")
    async with engine.connect() as connection:
        tables = await connection.run_sync(lambda sync: set(inspect(sync).get_table_names()))
    assert "match_events" not in tables
    await asyncio.to_thread(command.upgrade, config, "head")
    async with engine.connect() as connection:
        version = (
            await connection.execute(text("SELECT version_num FROM alembic_version"))
        ).scalar_one()
    assert version == "0001"


async def test_the_migrate_command_brings_an_empty_database_to_head(
    migrated_schema: None, engine: AsyncEngine, monkeypatch: pytest.MonkeyPatch
) -> None:
    from podvinsya.cli import main

    await asyncio.to_thread(command.downgrade, alembic_config(DATABASE_URL), "base")
    monkeypatch.setenv("PODVINSYA_DATABASE_URL", DATABASE_URL)
    assert await asyncio.to_thread(main, ["migrate"]) == 0
    async with engine.connect() as connection:
        tables = await connection.run_sync(lambda sync: set(inspect(sync).get_table_names()))
    assert "match_events" in tables
